nav:
  - Project Index: index.md
  - Homeway.io: homeway.md
  - OctoEverywhere.com: octoeverywhere.md
  - Baconit: baconit.md
  - CrossTxT: crosstxt.md
  - Prism: prism.md
  - Glow: glow.md
  - Kokka Koro: kokka-koro.md
  - Q World: qworld.md
  - Mixer Carl: mixer-carl.md
  - MixTok: mix-tok.md
  - Loyalty: loyalty.md
  - Thinking Of You: thinking-of-you.md
  - Crack The Whip: crack-the-whip.md
  - Instemote: instemote.md
  - Liquid Physics Wallpaper: liquid-physics-wallpaper.md
  - Next Bus: next-bus.md
  - Purdue Bus: purdue-bus.md
  - Purdue Menu: purdue-menu.md
  - TxTBack: txtback.md
  - Reddit Time Machine: reddit-time-machine.md
